spring.application.name=contextflow-ai
server.port=${PORT:8081}
spring.ai.openai.api-key=${OPENROUTER_API_KEY}
spring.ai.openai.base-url=https://openrouter.ai/api/v1


logging.level.org.springframework.ai=DEBUG